### ISSUE TITLE
增加新功能

### ISSUE THREAD

**Issue by diwrang** [dargoncat/UtilPlugin#20]
### 检查项

- [X] 我确认插件已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/dargoncat/UtilPlugin/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。

### 描述

增加SCP击杀回血，我们正在考虑增加一个新服务器来完整的实现你的插件功能。即我只需要你的插件来开服务器，作为插件测试服

### 原因

（示例）
我需要这个功能来xxxx。很多人都有xxxx的需求，但如果没有这个功能，就不能xxxx了。
CCBE--月姐

**Comment by tyIUc** [comment]
****
