### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LamCN** [dargoncat/UtilPlugin#27]
### 检查项

- [X] 我确认插件已为最新版，且最新版未修复这一bug。
- [X] 我已在 [Issues 页面](https://github.com/dargoncat/UtilPlugin/issues?q=is%3Aissue+) 中搜索，确认了这一 Bug 未被提交过。

### 描述

[2024-02-10 21:19:49.113 +08:00] [ERROR] [Exiled.Events] Method "OnSpawned" of the class "UtilPlugin.EventHandler" caused an exception when handling the event "Exiled.Events.Features.Event`1[[Exiled.Events.EventArgs.Player.SpawnedEventArgs, Exiled.Events, Version=8.8.0.0, Culture=neutral, PublicKeyToken=null]]"
                                 System.NullReferenceException: Object reference not set to an instance of an object
                                   at UtilPlugin.EventHandler.OnSpawned (Exiled.Events.EventArgs.Player.SpawnedEventArgs ev) [0x00020] in <c1db744b45604f02804e8373e4157f14>:0
                                   at Exiled.Events.Features.Event`1[T].InvokeNormal (T arg) [0x00028] in <8eab984dbf6048c9afb11c5a44184c52>:0

### 重现步骤

服务器端报错，一直在刷屏

**Comment by LamCN** [comment]
![286cd1eecf8a0700cab90d9374910284](https://github.com/dargoncat/UtilPlugin/assets/132809855/b2eeb268-9451-4976-b4ee-729283bac73b)
投票的计算有问题，一开始就是100%

**Comment by dargoncat** [comment]
需要提供配置文件及更加详细的后台日志

**Comment by dargoncat** [comment]
> ![286cd1eecf8a0700cab90d9374910284](https://private-user-images.githubusercontent.com/132809855/303840491-b2eeb268-9451-4976-b4ee-729283bac73b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDQ0NDYsIm5iZiI6MTcwNzY0NDE0NiwicGF0aCI6Ii8xMzI4MDk4NTUvMzAzODQwNDkxLWIyZWViMjY4LTk0NTEtNDk3Ni1iNGVlLTcyOTI4M2JhYzczYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwOTM1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjk5ZjI3NTFjY2Y5NTE3ZDE1YWVmNjg4NjVlYTc3ODUzZjQ2M2UxNjY0YTcyNTc4NjJjNmRlMGQwNjYxNzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U7aJSOcQEb1HMXkVf1Yam7cveC2LsdsXtUZ-CcOK6R8) 投票的计算有问题，一开始就是100%

投票同意率只计算已投票的人，如果需要更改同意率计算公式可以提出

**Comment by dargoncat** [comment]
目前是打算更改成未投票以0.3计入同意票

**Comment by LamCN** [comment]
> 需要提供配置文件及更加详细的后台日志

[config.txt](https://github.com/dargoncat/UtilPlugin/files/14232956/config.txt)

**Comment by LamCN** [comment]
> 需要提供配置文件及更加详细的后台日志

[Uploading localadminlogs.txt…]()

**Comment by LamCN** [comment]
> > ![286cd1eecf8a0700cab90d9374910284](https://private-user-images.githubusercontent.com/132809855/303840491-b2eeb268-9451-4976-b4ee-729283bac73b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc2NDQ0NDYsIm5iZiI6MTcwNzY0NDE0NiwicGF0aCI6Ii8xMzI4MDk4NTUvMzAzODQwNDkxLWIyZWViMjY4LTk0NTEtNDk3Ni1iNGVlLTcyOTI4M2JhYzczYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMVQwOTM1NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZjk5ZjI3NTFjY2Y5NTE3ZDE1YWVmNjg4NjVlYTc3ODUzZjQ2M2UxNjY0YTcyNTc4NjJjNmRlMGQwNjYxNzk2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.U7aJSOcQEb1HMXkVf1Yam7cveC2LsdsXtUZ-CcOK6R8) 投票的计算有问题，一开始就是100%
> 
> 投票同意率只计算已投票的人，如果需要更改同意率计算公式可以提出

投票事件结束后不投票的算作反对票

**Comment by LamCN** [comment]
> 需要提供配置文件及更加详细的后台日志

[localadminlogs.txt](https://github.com/dargoncat/UtilPlugin/files/14233055/localadminlogs.txt)
