### ISSUE TITLE
投票系统

### ISSUE THREAD

**Issue by LamCN** [dargoncat/UtilPlugin#28]
### 检查项

- [X] 我确认插件已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/dargoncat/UtilPlugin/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。

### 描述

投票踢人

### 原因

.callvote kick
方便没有管理踢人

**Comment by LamCN** [comment]
可以编辑系统核弹投票的可用时间

**Comment by dargoncat** [comment]
投票踢人好办，但是可以给个公式不？
就是什么情况下投票会通过

**Comment by LamCN** [comment]
> 投票踢人好办，但是可以给个公式不？ 就是什么情况下投票会通过

投票同意的超过当前服务器人数的70%通过，不投票的视为反对

**Comment by dargoncat** [comment]
问一下，你是哪个服的腐竹？ @LamCN
