### ISSUE TITLE
白月希的issue

### ISSUE THREAD

**Issue by diwrang** [dargoncat/UtilPlugin#30]
### 检查项

- [X] 我确认插件已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/dargoncat/UtilPlugin/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。

### 描述

加入SCP站立回血
开局30s内自动补票（变成DD）
加入SCP-2818，伤害很高的狙击枪，会把人发射出去，人会死，一发，最好用左轮的模型（要是做不了当我没说）

### 原因

我觉得有必要（）

**Comment by dargoncat** [comment]
等待当前其他事项完成后实现
