### ISSUE TITLE
补票

### ISSUE THREAD

**Issue by diwrang** [dargoncat/UtilPlugin#32]
### 检查项

- [X] 我确认插件已为最新版，且最新版未实现这一功能。
- [X] 我已在 [Issues 页面](https://github.com/dargoncat/UtilPlugin/issues?q=is%3Aissue+) 中搜索，确认了这一提案未被提交过。

### 描述

在回合开始一分钟以内，进入的人观察者自动变成D级人员

### 原因

有些人因为网络问题不能在开始之前进入服务器，管理员不可能一直都在，需要帮助补票

**Comment by dargoncat** [comment]
即日起停止对CCBE服务器的适应性更新,抱歉orz
